<a href="https://colab.research.google.com/github/maximo261199/FINAL/blob/main/hex%20Game.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import graphviz as gv

In [3]:
def drawDS(ds):
  graph = gv.Digraph("DisjointSet")
  graph.graph_attr['rankdir'] = "BT"
  for e, p in enumerate(ds):
    graph.node(str(e))
    if p >= 0:
      graph.edge(str(e), str(p))
  return graph

In [15]:
class DisjointSet:
  def __init__(self,n):
    self.n = n
    self.ds = [-1]*n

  def find(self,e):
    if self.ds[e] < 0:
      return e
    else:
      root = self.find(self.ds[e])
      self.ds[e] = root
      return root
    
  def union(self,a,b):
    a = self.find(a)
    b = self.find(b)

    if a == b: return
  
    if self.ds[a] < self.ds[b]:
      self.ds[a] += self.ds[b]
      self.ds[b] = a
    else:
      self.ds[b]+= self.ds[a]
      self.ds[a] = b
        

In [28]:
import numpy as np
import matplotlib.pyplot as plt

EMPTY = 0
BLACK = 1
WHITE = 2

class Hex:
  def __init__(self,n):
    self.n = n
    self.board = np.zeros((n,n), dtype = int)
    self.blackds = DisjointSet(n*n + 2)
    self.whiteds = DisjointSet(n*n + 2)
    for i in range(n):
      self.blackds.union(i, n*n)
      self.blackds.union((n-1)*n + i, n*n + 1)
      self.blackds.union(i*n, n*n)
      self.blackds.union(i * n + n - 1, n*n + 1)

  def move(self, i ,j,piece):
    if self.board[i,j] != EMPTY: return -1
    self.board[i,j] = piece
    ds = self.blackds if piece == BLACK else self.whiteds
    I1 = i * self.n + j
    adjs = [(i-1, j), (i-1,j+1),(i, j-1),(i, j+1), (i+1, j-1), (i+1,j)]
    for ii, jj in adjs:
      if ii < 0 or ii >= self.n or jj < 0 or jj >=  self.n: continue
      if self.board[ii,jj] == piece:
        I2 = ii * self.n + jj
        ds.union(I1,I2)

    N = self.n * self.n
    return piece if ds.find(N) == ds.find(N+1) else EMPTY

    

In [35]:
hex = Hex(5)
print(hex.board)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [36]:
hex.move(2,0,WHITE)

0

In [37]:
print(hex.board)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [2 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [38]:
hex.move(1,1,WHITE)
hex.move(1,2,WHITE)
hex.move(2,2,WHITE)
hex.move(3,1,WHITE)
hex.move(4,1,WHITE)
hex.move(4,2,WHITE)
hex.move(4,3,WHITE)
hex.move(3,4,WHITE)

0

In [39]:
print(hex.board)


[[0 0 0 0 0]
 [0 2 2 0 0]
 [2 0 2 0 0]
 [0 2 0 0 2]
 [0 2 2 2 0]]
